import { useEffect, useState, useRef } from "react";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";
import API from "../services/api";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const DashboardStudent = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [timetable, setTimetable] = useState([]);
  const [semester, setSemester] = useState("");
  const [section, setSection] = useState("");
  const [loading, setLoading] = useState(false);
  const tableRef = useRef();

  const handleLogout = () => {
    logout();
    navigate("/");
  };

  useEffect(() => {
    if (user?.semester && user?.section) {
      fetchTimetable(user.semester, user.section);
    }
  }, [user]);

  const fetchTimetable = async (semester, section) => {
    try {
      setLoading(true);
      const res = await API.get(`/timetable/student/${semester}/${section}`);
      setTimetable(res.data.data || []);
      setSemester(res.data.semester);
      setSection(res.data.section);
    } catch (err) {
      console.error("Error fetching timetable:", err);
      setTimetable([]);
    } finally {
      setLoading(false);
    }
  };

  const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const timeSlots = [
    "9:00–10:00",
    "10:00–11:00",
    "11:00–12:00",
    "12:00–1:00",
    "1:00–2:00",
    "2:00–3:00",
    "3:00–4:00",
  ];

  // 🧾 Download timetable as PDF
  const downloadPDF = async () => {
    const input = tableRef.current;
    if (!input) return;

    const clone = input.cloneNode(true);
    document.body.appendChild(clone);
    clone.style.position = "absolute";
    clone.style.left = "-9999px";
    clone.style.background = "#ffffff";

    // Sanitize OKLCH colors
    const sanitizeColors = (el) => {
      const computed = window.getComputedStyle(el);
      for (const prop of ["color", "backgroundColor", "borderColor"]) {
        const val = computed[prop];
        if (val && val.includes("oklch")) el.style[prop] = "#f8fafc";
      }
      for (const child of el.children) sanitizeColors(child);
    };
    sanitizeColors(clone);

    const style = document.createElement("style");
    style.innerHTML = `
      * { font-family: 'Inter', sans-serif !important; color: #111827 !important; }
      table { border-collapse: collapse !important; width: 100% !important; }
      th, td { border: 1px solid #000 !important; padding: 6px !important; text-align: center !important; }
      th { background: rgb(219,234,254) !important; }
      td:first-child { background: rgb(224,242,254) !important; font-weight: 600 !important; }
      .lunch-cell { background: rgb(255,247,204) !important; font-weight: bold !important; }
    `;
    clone.prepend(style);

    try {
      const canvas = await html2canvas(clone, {
        scale: 3,
        backgroundColor: "#ffffff",
        logging: false,
        useCORS: true,
      });
      document.body.removeChild(clone);

      const pdf = new jsPDF("landscape", "mm", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgData = canvas.toDataURL("image/png");
      const aspectRatio = canvas.width / canvas.height;

      let imgWidth = pageWidth - 10;
      let imgHeight = imgWidth / aspectRatio;
      if (imgHeight > pageHeight - 45) {
        imgHeight = pageHeight - 45;
        imgWidth = imgHeight * aspectRatio;
      }

      const x = (pageWidth - imgWidth) / 2;
      const y = 45;

      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.text("MORADABAD INSTITUTE OF TECHNOLOGY, MORADABAD", pageWidth / 2, 15, { align: "center" });
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(12);
      pdf.text("Department of Computer Science & Engineering - Timetable", pageWidth / 2, 22, { align: "center" });

      const studentName = user?.name || "Student";
      const sem = semester || "N/A";
      const sec = section || "N/A";
      const academicYear = "2025–26";

      pdf.setFontSize(11);
      pdf.text(`Student: ${studentName}   |   Semester: ${sem}   |   Section: ${sec}   |   Academic Year: ${academicYear}`, pageWidth / 2, 30, { align: "center" });

      pdf.addImage(imgData, "PNG", x, y, imgWidth, imgHeight);
      const date = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
      pdf.setFontSize(10);
      pdf.setTextColor(90);
      pdf.text(`Generated by EduChrono on ${date}`, pageWidth / 2, pageHeight - 8, { align: "center" });
      pdf.save(`Timetable_${studentName}.pdf`);
    } catch (err) {
      console.error("PDF Error:", err);
      alert("Error generating PDF.");
    }
  };

  return (
    <div className="p-8 bg-gray-50 min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-blue-700">
            Student Dashboard – {user?.name}
          </h1>
          {(semester || section) && (
            <p className="text-gray-600 mt-1">
              🎓 Semester: <span className="font-semibold">{semester}</span> | 📘 Section:{" "}
              <span className="font-semibold">{section}</span>
            </p>
          )}
        </div>
        <button onClick={handleLogout} className="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600">
          Logout
        </button>
      </div>

      <div className="bg-white shadow rounded-xl p-6">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-lg font-medium text-gray-800">📘 My Class Timetable</h2>
          {timetable.length > 0 && (
            <button onClick={downloadPDF} className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition">
              📄 Download PDF
            </button>
          )}
        </div>

        {loading && <p className="text-gray-500">Loading timetable...</p>}

        {!loading && timetable.length > 0 && (
          <div ref={tableRef} className="overflow-x-auto mt-6">
            <table className="border-collapse border border-gray-400 w-full text-center">
              <thead className="bg-green-100">
                <tr>
                  <th className="border border-gray-400 p-2 w-28">Day</th>
                  {timeSlots.map((slot) => (
                    <th key={slot} className="border border-gray-400 p-2 text-sm font-semibold text-gray-700">
                      {slot}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {days.map((day, dayIndex) => (
                  <tr key={day}>
                    <td className="border border-gray-400 p-2 font-semibold bg-gray-50">{day}</td>

                    {timeSlots.map((slot, slotIndex) => {
                      if (slot === "1:00–2:00") {
                        if (dayIndex === 0)
                          return (
                            <td
                              key="lunch"
                              rowSpan={days.length}
                              className="border border-gray-400 bg-yellow-100 font-semibold text-gray-800 text-center align-middle"
                            >
                              🍱 LUNCH BREAK
                            </td>
                          );
                        return null;
                      }

                      // 🧪 Detect 2-hour sessions (Labs, Tutorials, COE)
                      const twoHourEntries = timetable.filter(
                        (t) =>
                          t.day?.toLowerCase() === day.toLowerCase() &&
                          t.time_slot?.startsWith(slot) &&
                          (t.time_slot?.includes("+") ||
                            ["P", "T", "COE"].includes(t.type))
                      );

                      if (twoHourEntries.length > 0) {
                        const typeColor = {
                          P: "bg-green-50",
                          T: "bg-blue-50",
                          COE: "bg-orange-50",
                        };
                        const icon = {
                          P: "🧪",
                          T: "📘",
                          COE: "🏛️",
                        };
                        return (
                          <td
                            key={`${day}-${slot}-twohour`}
                            colSpan={2}
                            className={`border border-gray-400 p-2 whitespace-pre-line text-sm text-gray-800 ${typeColor[twoHourEntries[0].type]}`}
                          >
                            {twoHourEntries.map((entry, idx) => (
                              <div key={idx} className="mb-1 border-b border-gray-300 pb-1 last:border-0 rounded-md p-1">
                                <span className="block font-semibold text-gray-900">
                                  {icon[entry.type]} {entry.subject} ({entry.type}
                                  {entry.batch ? ` - ${entry.batch}` : ""})
                                </span>
                                <span className="block text-gray-700">{entry.room}</span>
                                <span className="block text-gray-500">{entry.faculty}</span>
                              </div>
                            ))}
                          </td>
                        );
                      }

                      // 🧩 1-hour Lectures / PDP
                      const oneHourEntries = timetable.filter(
                        (t) =>
                          t.day?.toLowerCase() === day.toLowerCase() &&
                          t.time_slot?.toLowerCase() === slot.toLowerCase()
                      );

                      if (oneHourEntries.length === 0)
                        return (
                          <td key={`${day}-${slot}`} className="border border-gray-400 p-2 text-sm text-gray-700">
                            -
                          </td>
                        );

                      return (
                        <td key={`${day}-${slot}`} className="border border-gray-400 p-2 whitespace-pre-line text-sm text-gray-800">
                          {oneHourEntries.map((entry, idx) => {
                            const bgMap = {
                              L: "bg-white",
                              PDP: "bg-purple-50",
                            };
                            const iconMap = {
                              L: "📖",
                              PDP: "🧠",
                            };
                            return (
                              <div key={idx} className={`mb-1 border-b border-gray-300 pb-1 last:border-0 rounded-md p-1 ${bgMap[entry.type]}`}>
                                <span className="block font-semibold text-gray-900">
                                  {iconMap[entry.type] || ""} {entry.subject} ({entry.type}
                                  {entry.batch ? ` - ${entry.batch}` : ""})
                                </span>
                                <span className="block text-gray-700">{entry.room}</span>
                                <span className="block text-gray-500">{entry.faculty}</span>
                              </div>
                            );
                          })}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default DashboardStudent;
